name: echelon_app

services:
  grpc-server:
    build: .
    ports:
      - ${SERVICE_PORT}:54320
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
    networks:
      - echelon_network
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - echelon_network
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  echelon_network: